---
language: go

install: |
  go get -t ./...
  go install github.com/onsi/ginkgo/ginkgo

jobs:
  include:
    - stage: test
      script: ginkgo -r -p
    - state: build
      script: |
        for os in linux darwin windows; do
          ext=""
          if [ "$os" = "windows" ]; then
            ext=".exe"
          fi

          echo "building $os binary..."
          GOOS=$os go build \
            --ldflags "-X github.com/vito/booklit.Version=$(cat version/version)" \
            -o assets/booklit_${os}_amd64${ext} \
            github.com/vito/booklit/cmd/booklit
        done
      deploy:
        provider: s3
        bucket: concurse-rulez-test-bucket
        skip_cleanup: true
        region: us-west-1
        local_dir: assets
