---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang

inputs:
- name: ci
- name: booklit
- name: version
  optional: true

outputs:
- name: assets

caches:
- path: gopath/

run:
  path: ci/tasks/scripts/build
