version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/vito/booklit

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      - run: mkdir -p artifacts
      - run: go build -o artifacts/blah github.com/vito/booklit/cmd/booklit

      - save_cache:
          key: booklit-artifact
          paths: [artifacts/blah]

  publish:
    docker:
      - image: circleci/golang:1.8

    working_directory: /tmp

    steps:
      - restore_cache:
          keys: [booklit-artifact]

      - run: ls -al

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - publish:
        requires:
          - build
