version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/vito/booklit

    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

      - run: mkdir -p artifacts
      - run: go build -o artifacts/blah github.com/vito/booklit/cmd/booklit

      - persist_to_workspace:
          root: artifacts
          paths:
            - blah

      - save_cache:
        key: booklit-{{ checksum artifacts/blah }}
        paths: [ artifacts/blah ]


  publish:
    docker:
      - image: circleci/golang:1.8

    working_directory: /tmp

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - restor_cache:
        keys: [ booklit-{{ checksum workspace/blah }} ]

      - run: find .

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - publish:
        requires:
          - build
