---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang}

inputs:
- name: booklit
  path: gopath/src/github.com/vito/booklit
- name: version

outputs:
- name: assets

caches:
- path: depspath/
- path: gopath/pkg/

run:
  path: gopath/src/github.com/vito/booklit/ci/build
